spring:
  application:
    name: tlias-web-management
  #配置数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 212414
  servlet:
    multipart:
      # 最大单个文件上传大小
      max-file-size: 10MB
      # 最大单个请求大小（包括所有文件和表单数据）
      max-request-size: 100MB

mybatis:
  configuration:
    #开启mybatis日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
